user_type: multiuser_aggregate
user_range: [0, 2]
num_data_points: 200

provide_buffers: False
provide_labels: False
provide_num_data_points: True

# Local differential privacy:
local_diff_privacy:
  gradient_noise: 0.1
  input_noise: 0.0
  distribution: gaussian
  per_example_clipping: 1.0

num_local_updates: 2 # Set to more to do fedAVG
num_data_per_local_update_step: 100 # Every step is taken on a different sample
local_learning_rate: 0.0001
provide_local_hyperparams: True # Provide local_learning_rate, num_data_per_local_update_step, num_local_updates to server